### ISSUE TITLE
Data saved is not persistent on the disk

### ISSUE THREAD

**Issue by uc-apa** [mogol/flutter_realm#11]
I have build and run the example project in this repository. Data is being stored successfully, but it is not persistent. When I go back the page and then come again, the saved data is missing. Please help me what am I missing.
[Demo Video](https://screencast.com/t/tLx9dLoa)

**Comment by uc-apa** [comment]
Also if you can specify, where is the default.realm file is put then it will be help to browse that with realm browser. It used to be in the app's document directory in react native but I did not find any realm file in document directory of flutter app in simulator.
![image](https://user-images.githubusercontent.com/25792136/75449538-2724a900-5993-11ea-9347-ab0cce335c68.png)

**Comment by gonharry** [comment]
On the RealmProvider set a Configuration with a persistant name or ID.

`@override
  void initState() {
    super.initState();
    final configuration = Configuration(inMemoryIdentifier: "your_persistan_ID");
    realm = Realm.open(configuration);
  }`

**Comment by uc-apa** [comment]
This solution worked. Thank you very much. But I would really like to know exactly where the realm file is saved so that I would be able to visualize the database with the realm browser. Whether it store a default.realm file same as RN or some different approach is followed.

**Comment by vavadiyahiren** [comment]
> On the RealmProvider set a Configuration with a persistant name or ID.
> 
> `@override void initState() { super.initState(); final configuration = Configuration(inMemoryIdentifier: "your_persistan_ID"); realm = Realm.open(configuration); }`

I did this but even after adding the persistence id it seems it is storing in memory so after killing the application data is no longer available. Am I missing some configuration here?
