### ISSUE TITLE
Database security

### ISSUE THREAD

**Issue by uc-apa** [mogol/flutter_realm#12]
I would like to know how safe is it to use this package in a large scale app or in production. Will someone else be able to access the database/tables created in my app, like sqflite. The sqflite offers encryption for this case. Please tell me also that where the database file is saved like it was saved in document directory of the app in react native namely default.realm. I did not find any such file here. Thanks.

**Comment by mogol** [comment]
@uc-apa please check [Realm documentation](https://realm.io/docs), [forums](https://community.mongodb.com/c/realm) or [SO](https://stackoverflow.com/questions/tagged/realm)
