### ISSUE TITLE
Realm init problem

### ISSUE THREAD

**Issue by dimityrivanov** [mogol/flutter_realm#5]
I followed the setup but my class is not translated to realmObject and its always saying me class does not exist, also when I use the example app when I create 'Product' close the app and open in again that 'Product' does not exist.

Is there something that I am missing ?

**Comment by mogol** [comment]
>when I use the example app when I create 'Product' close the app and open in again that 'Product' does not exist.

Example app uses in-memory realm. If you remove inMemoryIdentifier, it should persist data across launches. 
https://github.com/mogol/flutter_realm/blob/ce3e68c712972a976b8f01a1d93fe470f86af150/example/lib/helpers/local_realm_provider.dart#L20

**Comment by dimityrivanov** [comment]
@mogol That works thanks, Maybe we should add it to the documentation

**Comment by vavadiyahiren** [comment]
@mogol can you help me to track where default.realm files can be stored in android devices ?
