### ISSUE TITLE
help me out to connect realm with flutter auth login functionality

### ISSUE THREAD

**Issue by manishydv** [mogol/flutter_realm#9]
Hi,
I new on flutter.try authentication user application show as below attachment.
and I stack with realm DB implementation with flutter (no document for flutter+realm).

I used this link - "https://github.com/mogol/flutter_realm" example folder for reference to connect the realm DB.

if some give short "DEMO CODE" user registration data save on realm data.

I'm trying to resolve this from the last 5 days.
![Untitled](https://user-images.githubusercontent.com/51132893/74029133-05f31d00-49d2-11ea-94e4-dbd9ad0eca58.png)

**Comment by mogol** [comment]
Hi @manishydv 
ReamDB is a local database and an alternative to SQLite and Core Data. See [docs](https://realm.io/docs#realm-database). So there is no need in user registration. 

If you are interested in [Realm Sync](https://docs.realm.io/sync/), you can see example [there](https://github.com/mogol/flutter_realm/blob/master/example/lib/sync/sync.dart)
